version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "0libote"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
